### ISSUE TITLE
E2E testing roadmap

### ISSUE THREAD

**Issue by odahcam** [zxing-js/library#347]
- [x] choose testing lib. (gonna be cypress)
- [x] integrate first test. (qrcode webcam scanning)
- [ ] create test project which consumes the latest build artefacts. (docs would need some rework to fit this requirement, like bundling, etc.)
- [ ] integrate test run into CI/CD.
- [ ] enjoy e2e tests.

**Comment by odahcam** [comment]
Currently using statically served project files and accessing edited version of a docs file. In near future I pretend to rewrite the "docs" with better tools.

**Comment by odahcam** [comment]
Got E2E tests working with Travis, now we just need to create more and more tests.

**Comment by odahcam** [comment]
I'm not sure what tests we can create in here since the browser layer is separating from the library, but let's start thinking about it.
